### ISSUE TITLE
Did the SAT binding in CryptoMiniSat not work?

### ISSUE THREAD

**Issue by msoos** [lummax/python-cryptominisat#1]
Hi! I'm the author of CryptoMiniSat. I'm wondering why you made this package :) Was the binding in the original package not sufficient? Or did it not work? Or was it not intuitive to use? I'm curious! Original package:

https://github.com/msoos/cryptominisat
(binding builds if you use cmake and python 2/3 is installed)

Thanks,

Mate

**Comment by lukasoyen** [comment]
Hey, I worked on this quite some time ago and can't really remember what the limitations of the `cryptominisat` python bindings were at the time. Note, this was started when the bindings looked like this https://github.com/msoos/cryptominisat/tree/f2474a9970278beb06d224f968ea4f50075c5f86/python (might have been missing Python3 support?).

I am happy to add a deprecation note and link back to your bindings if that is your concern.

**Comment by msoos** [comment]
Sure, no worries, I was just curious to get some feedback! Yeah, things have improved since :) Thanks for the feedback! Cheers!
